name:                        Release

on:
  push:
    branches:                [main]

jobs:
  # lint code.
  lint:
    name:                    Lint
    runs-on:                 ubuntu-latest

    steps:
      - name:                Checkout
        uses:                actions/checkout@v3
      # only lint on actual code changes.
      - name:                Lint
        uses:                norio-nomura/action-swiftlint@3.2.1
        env:
          DIFF_BASE:         ${{ github.event.push.before }}
        with:
          args:              --strict

  # build the library.
  build:
    name:                    Build
    needs:                   lint
    runs-on:                 macos-latest

    steps:
      - name:                Checkout
        uses:                actions/checkout@v3
      # only build on actual code changes.
      - uses:                dorny/paths-filter@v2
        id:                  changes
        with:
          base:              ${{ github.event.push.before }}
          filters:           |
            src:
              - '**/*.swift'
      - name:                Build
        if:                  steps.changes.outputs.src == 'true'
        run:                 swift build

  # release a new version.
  release:
    name:                    Release
    needs:                   build
    runs-on:                 ubuntu-latest

    steps:
      - name:              Release version
        id:                  release-version
        uses:                tomtom-international/commisery-action/bump@v1
        with:
          token:             ${{ secrets.GITHUB_TOKEN }}
          create-release:    true
          create-tag:        true
          version-prefix:    v

  # create docs.
  docs:
    name:                    Docs
    needs:                   release
    runs-on:                 ubuntu-latest

    steps:
      # checkout the `main` branch.
      - name:                Checkout
        id:                  checkout
        uses:                actions/checkout@v3
        with:
          token:             ${{ secrets.GITHUB_TOKEN }}
          ref:               main
      # only push docs on actual code changes.
      - uses:                dorny/paths-filter@v2
        id:                  changes
        with:
          base:              ${{ github.event.push.before }}
          filters:           |
            src:
              - '**/*.swift'
              - '**/push.yml'
      # create documentation for `DropView`.
      - name:                Docs (DropView)
        if:                  steps.changes.outputs.src == 'true'
        uses:                SwiftDocOrg/swift-doc@master
        with:
          base-url:          "https://sbertix.github.io/DropView/DropView/"
          format:            "html"
          inputs:            "Sources"
          module-name:       DropView
          output:            docs/DropView
      # update permissions.
      - name:                Update Permissions
        if:                  steps.changes.outputs.src == 'true'
        run:                 'sudo chown --recursive $USER docs'
      # publish to GitHub pages.
      - name:                Publish
        if:                  steps.changes.outputs.src == 'true'
        uses:                JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN:      ${{ secrets.CHATOPS_PAT }}
          BRANCH:            gh-pages
          FOLDER:            docs
